---
- name: Check slirp4netns exists
  stat:
    path: "/usr/bin/slirp4netns"
  register: old_slirp4netns_installed

- name: Delete slirp4netns if exists
  file:
    path: "{{ item.stat.path }}"
    state: absent
  with_items:
    - "{{ old_slirp4netns_installed }}"
  when: item.stat.exists | bool
  changed_when: false

- name: get latest slirp4netns version
  shell: |
    set -o pipefail
    curl -sSL https://api.github.com/repos/rootless-containers/slirp4netns/releases | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | head -n1
  args:
    executable: /bin/bash
  register: new_slirp4netns_version
  changed_when: false

- name: Get slirp4netns download checksum
  shell: |
    set -o pipefail
    curl -sSL https://github.com/rootless-containers/slirp4netns/releases/download/{{ new_slirp4netns_version.stdout }}/SHA256SUMS | grep 'x86_64' | awk '{print $1}'
  args:
    executable: /bin/bash
  register: new_slirp4netns_checksum
  changed_when: false

- name: Install latest slirp4netns
  get_url:
    url: https://github.com/rootless-containers/slirp4netns/releases/download/{{ new_slirp4netns_version.stdout }}/slirp4netns-x86_64
    dest: "/usr/bin/slirp4netns"
    mode: 0755
    checksum: sha256:{{ new_slirp4netns_checksum.stdout }}
  changed_when: false
