---

- name: install docker packages
  action: >
    {{ ansible_pkg_mgr }} name={{ docker_new_packages }} state=present update_cache=yes
  register: pkg_install_requirements
  until: pkg_install_requirements is succeeded
  retries: 3
  changed_when: false
  notify:
    - Enable docker services
    - CentOS - iptables fix for docker
    - Debian - iptables fix for docker
    - Control docker with daemon.json
    - Set default OCI runtime
    - Daemon reload
    - Restart docker service

- name: add user(s) to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users_list }}"

- name: Add user(s) to sudoers
  lineinfile:
    dest: "/etc/sudoers.d/{{ item }}"
    state: present
    regexp: '{{ item }}'
    line: '{{ item }}     ALL=(ALL) NOPASSWD:ALL'
    mode: 0644
    create: yes
    validate: 'visudo -cf %s'
  with_items:
    - "{{ docker_users_list }}"
