---
- name: install docker packages
  action: >
    {{ ansible_pkg_mgr }} name={{ docker_new_packages }} state=present update_cache=yes
  register: pkg_install_requirements
  until: pkg_install_requirements is succeeded
  retries: 3
  changed_when: false

- name: service unit file fix
  shell: |
    set -o pipefail
     sed -i "s/fd:\/\//unix:\/\//g" /lib/systemd/system/docker.service
  args:
    executable: /bin/bash
  changed_when: false

- name: RedHat - iptables fix for docker
  shell: |
    set -o pipefail
    sed -i '/ExecStart/s/$/ --iptables=false/' /usr/lib/systemd/system/docker.service
  args:
    executable: /bin/bash
  changed_when: false
  when:
    - ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 8
    - not docker_rootless_install | bool

- name: service - daemon reload
  shell: |
    set -o pipefail
     systemctl daemon-reload
  args:
    executable: /bin/bash
  changed_when: false

# https://forums.docker.com/t/failing-to-start-dockerd-failed-to-create-nat-chain-docker/78269
- name: Debian - iptables fix for docker
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items:
    - "{{ debian_iptables_alternatives }}"
  when: ansible_distribution == 'Debian' and not docker_rootless_install | bool

- name: add user(s) to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users_list }}"

- name: Add user(s) to sudoers
  lineinfile:
    dest: "/etc/sudoers.d/{{ item }}"
    state: present
    regexp: "{{ item }}"
    line: "{{ item }}     ALL=(ALL) NOPASSWD:ALL"
    mode: 0644
    create: yes
    validate: "visudo -cf %s"
  with_items:
    - "{{ docker_users_list }}"
  notify:
    - Restart service

- name: Flush handlers
  meta: flush_handlers
