---

- name: install docker packages
  action: >
    {{ ansible_pkg_mgr }} name={{ docker_new_packages }} state=present update_cache=yes
  register: pkg_install_requirements
  until: pkg_install_requirements is succeeded
  retries: 3
  changed_when: false

- name: add user(s) to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users_list }}"

- name: Add user(s) to sudoers
  lineinfile:
    dest: "/etc/sudoers.d/{{ item }}"
    state: present
    regexp: '{{ item }}'
    line: '{{ item }}     ALL=(ALL) NOPASSWD:ALL'
    mode: 0644
    create: yes
    validate: 'visudo -cf %s'
  with_items:
    - "{{ docker_users_list }}"
  notify:
    - Enable docker services
    - CentOS - iptables fix for docker
    - Debian - iptables fix for docker
    - Control docker using daemon.json
    - Daemon reload
    - Start docker service

- name: Flush handlers
  meta: flush_handlers

#- name: Control docker using daemon.json
#  shell: |
#    set -o pipefail
#    sudo sed -i 's/\ -H\ fd:\/\///g' /lib/systemd/system/docker.service
#  become: yes
#  args:
#    executable: /bin/bash
#  changed_when: false

#- name: Create docker config folder
#  file:
#    state: directory
#    owner: 'root'
#    group: 'root'
#    mode: 0755
#    path: "{{ item }}"
#  changed_when: false
#  with_items:
#    - "/etc/docker"
