---
- name: Reload sysctl
  shell: |
    set -o pipefail
    sysctl -p /etc/sysctl.d/00-rootless.conf
  args:
    executable: /bin/bash
  changed_when: false

- name: Update grub bootloader
  shell: |
    set -o pipefail
    update-grub2
  args:
    executable: /bin/bash
  changed_when: False

- name: daemon reload
  systemd:
    daemon_reload: yes

- name: daemon reload
  systemd:
    daemon_reload: yes
  changed_when: false
  when: not docker_rootless_install | bool

- name: Enable services
  systemd:
    enabled: yes
    name: "{{ item }}"
  changed_when: false
  with_items:
    - "{{ docker_services }}"
  when: not docker_rootless_install | bool

- name: Start service
  systemd:
    name: docker
    state: started
  changed_when: false
  when: not docker_rootless_install | bool

- name: Restart service
  systemd:
    name: docker
    state: restarted
  changed_when: false
  when: not docker_rootless_install | bool
