---
- name: Converge
  hosts: all
  vars:
    docker_rootless_install: true
    docker_users:
      - tinashe
  tasks:

    - name: Add test users
      user:
        name: "{{ item }}"
        password: ''
        shell: "/bin/bash"
      with_items:
        - "{{ docker_users }}"

    - name: "Include hybridadmin.docker"
      include_role:
        name: "ansible-role-docker"
#        name: "hybridadmin.docker"
