---
- name: Converge
  hosts: all
  vars:
    docker_users:
      - tinashe
  tasks:
    - name: Add test users
      user:
        name: "{{ item }}"
        shell: "/bin/bash"
      with_items:
        - "{{ docker_users }}"

    - name: "Include hybridadmin.docker"
      include_role:
        name: "hybridadmin.docker"
